"""Add cloudinary secure fields to invoice

Revision ID: 0934a7ccf9f1
Revises: fix_user_and_invoice
Create Date: 2025-01-27 13:01:22.406481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0934a7ccf9f1'
down_revision = 'fix_user_and_invoice'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_secure_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('cloudinary_signature', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('wholesaler', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wholesaler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_signature')
        batch_op.drop_column('cloudinary_secure_url')

    # ### end Alembic commands ###
