"""Add MarginSuggestion model, update Invoice and ProcessingProgress

Revision ID: dc51250f37fe
Revises: 2b7e2a3642ec
Create Date: 2025-01-26 19:57:04.158344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc51250f37fe'
down_revision = '2b7e2a3642ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('margin_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('suggested_margin', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('area_type', sa.String(length=50), nullable=True),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('area_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('processing_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ui_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_progress', schema=None) as batch_op:
        batch_op.drop_column('ui_message')
        batch_op.drop_column('stage_details')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('area_type')
        batch_op.drop_column('location')

    op.drop_table('margin_suggestion')
    # ### end Alembic commands ###
